### ISSUE TITLE
Transcode non 16:9 format

### ISSUE THREAD

**Issue by grosalex** [ypresto/android-transcoder#15]
Hi,
Sorry for the questions but is there a way to transcode non 16:9 format?

Thanks for the lib,

**Comment by ypresto** [comment]
It is technically possible, by passing your own MediaFormatStrategy to transcodeVideo method.
But it is not guaranteed to be correctly transcoded because [Android Compatibility Test Suite](https://source.android.com/compatibility/cts/) only tests for [Video Encoding Recommendations](http://developer.android.com/intl/ja/guide/appendix/media-formats.html#recommendations).
For example, Nexus 4 does not support `MediaFormatStrategyPresets.createExportPreset960x540Strategy()`.

**Comment by grosalex** [comment]
Ok thanks a lot for your answear.

**Comment by adrianknight89** [comment]
@ypresto Isn't 960x540 a 16:9 format though? Why is it broken on Nexus 4? I thought you meant non-16:9 is broken.
